const ImageVars = {

    outputIconArray : [require('../Common/img/out-dark-lamp1.png'),require('../Common/img/out-dark-lamp2.png'),
                       require('../Common/img/out-dark-lamp3.png'),require('../Common/img/out-dark-lamp4.png'),
                       require('../Common/img/out-dark-lamp5.png'),
                       require('../Common/img/out-dark-lamp6.png'),require('../Common/img/out-dark-lamp7.png'),
                       require('../Common/img/out-dark-lamp8.png'),require('../Common/img/out-dark-kitchen.png'),
                       require('../Common/img/out-dark-ref.png'),require('../Common/img/out-dark-speaker.png'),
                       require('../Common/img/common-dark-curtain.png'), require('../Common/img/common-dark-closecurtain.png'),
                       require('../Common/img/out-dark-garden.png'),require('../Common/img/out-dark-split.png'),
                       require('../Common/img/out-dark-bathroom.png'),require('../Common/img/out-dark-wc.png'),
                       require('../Common/img/out-dark-fan.png'), require('../Common/img/common-dark-dinning.png'),
                       require('../Common/img/out-dark-faucet.png'), require('../Common/img/out-dark-valve.png'),
                       require('../Common/img/out-dark-watering.png')],

    outputIconLightArray : [require('../Common/img/out-light-lamp1.png'),require('../Common/img/out-light-lamp2.png'),
                      require('../Common/img/out-light-lamp3.png'),require('../Common/img/out-light-lamp4.png'),
                      require('../Common/img/out-light-lamp5.png'),
                      require('../Common/img/out-light-lamp6.png'),require('../Common/img/out-light-lamp7.png'),
                      require('../Common/img/out-light-lamp8.png'),require('../Common/img/out-light-kitchen.png'),
                      require('../Common/img/out-light-ref.png'),require('../Common/img/out-light-speaker.png'),
                      require('../Common/img/common-light-curtain.png'), require('../Common/img/common-light-closecurtain.png'),
                      require('../Common/img/out-light-garden.png'),require('../Common/img/out-light-split.png'),
                      require('../Common/img/out-light-bathroom.png'),require('../Common/img/out-light-wc.png'),
                      require('../Common/img/out-light-fan.png'), require('../Common/img/common-light-dinning.png'),
                      require('../Common/img/out-light-faucet.png'), require('../Common/img/out-light-valve.png'),
                      require('../Common/img/out-light-watering.png')],

    locationIconArray : [require('../Common/img/out-dark-lamp1.png'),require('../Common/img/out-dark-lamp2.png'),
                       require('../Common/img/out-dark-lamp3.png'),require('../Common/img/out-dark-lamp4.png'),
                       require('../Common/img/out-dark-lamp5.png'),require('../Common/img/out-dark-kitchen.png'),
                       require('../Common/img/out-dark-ref.png'),require('../Common/img/out-dark-speaker.png'),
                        require('../Common/img/out-dark-garden.png'),require('../Common/img/out-dark-split.png'),
                        require('../Common/img/out-dark-bathroom.png'),require('../Common/img/out-dark-wc.png'),
                        require('../Common/img/common-dark-bedroom.png'),require('../Common/img/common-dark-bedroom1.png'),
                        require('../Common/img/common-dark-bedroom2.png'), require('../Common/img/common-dark-dinning.png')],
    
    locationIconLightArray : [require('../Common/img/out-light-lamp1.png'),require('../Common/img/out-light-lamp2.png'),
                       require('../Common/img/out-light-lamp3.png'),require('../Common/img/out-light-lamp4.png'),
                       require('../Common/img/out-light-lamp5.png'),require('../Common/img/out-light-kitchen.png'),
                       require('../Common/img/out-light-ref.png'),require('../Common/img/out-light-speaker.png'),
                      require('../Common/img/out-light-garden.png'),require('../Common/img/out-light-split.png'),
                      require('../Common/img/out-light-bathroom.png'),require('../Common/img/out-light-wc.png'),
                      require('../Common/img/common-light-bedroom.png'),require('../Common/img/common-light-bedroom1.png'),
                      require('../Common/img/common-light-bedroom2.png'), require('../Common/img/common-light-dinning.png')],

    scenarioIconArray : [require('../Common/img/out-dark-lamp1.png'),require('../Common/img/out-dark-lamp2.png'),
                       require('../Common/img/out-dark-lamp3.png'),require('../Common/img/out-dark-lamp4.png'),
                       require('../Common/img/out-dark-lamp5.png'),require('../Common/img/out-dark-kitchen.png'),
                       require('../Common/img/out-dark-ref.png'),require('../Common/img/out-dark-speaker.png'),
                       require('../Common/img/common-dark-curtain.png'), require('../Common/img/common-dark-closecurtain.png'),
                       require('../Common/img/common-dark-cake.png'),require('../Common/img/common-dark-closedoor.png'),
                       require('../Common/img/common-dark-sleep.png'),require('../Common/img/common-dark-night.png'),
                       require('../Common/img/common-dark-opendoor.png'), require('../Common/img/common-dark-dinning.png'),
                       require('../Common/img/out-dark-airplane.png'),
                        require('../Common/img/out-dark-faucet.png'), require('../Common/img/out-dark-valve.png'),
                       require('../Common/img/out-dark-watering.png')],

   scenarioIconLightArray : [require('../Common/img/out-light-lamp1.png'),require('../Common/img/out-light-lamp2.png'),
                          require('../Common/img/out-light-lamp3.png'),require('../Common/img/out-light-lamp4.png'),
                          require('../Common/img/out-light-lamp5.png'),require('../Common/img/out-light-kitchen.png'),
                          require('../Common/img/out-light-ref.png'),require('../Common/img/out-light-speaker.png'),
                          require('../Common/img/common-light-curtain.png'), require('../Common/img/common-light-closecurtain.png'),
                          require('../Common/img/common-light-cake.png'),require('../Common/img/common-light-closedoor.png'),
                          require('../Common/img/common-light-sleep.png'),require('../Common/img/common-light-night.png'),
                          require('../Common/img/common-light-opendoor.png'), require('../Common/img/common-light-dinning.png'),
                          require('../Common/img/out-light-airplane.png'),
                          require('../Common/img/out-light-faucet.png'), require('../Common/img/out-light-valve.png'),
                          require('../Common/img/out-light-watering.png')],

    commonIconArray: [
         require('../Common/img/common-light-mic.gif')
    ]
}

export default ImageVars;
