const Commands = {

    // ERROR
    ERROR_BAD_REQUEST :  0x01,
    ERROR_TIMEOUT : 0x02,

    // MOD
    MOD_CONFIG : 0x40,

    // REQUEST
    REQ_INPUT : 0x01,
    REQ_OUTPUT : 0x02,
    REQ_DATE_TIME : 0x03,
    REQ_SCENARIO : 0x04,
    REQ_SCHEDULE : 0x05,
    REQ_REMOTE_IR : 0x06,
    REQ_INPUT_EVENT : 0x08,
    REQ_CURTAIN : 0x09,
    REQ_LOGIN : 0x33,
    REQ_SETUP : 0x34,
    REQ_MODULE : 0x35,
//    REQ_TEMPERATURE : 0x0C,
    REQ_RESET_TO_FACTORY : 0x0D,
    REQ_TABLET_MB_GENERAL : 0x0F,
    REQ_TABLET_MB_COM : 0x0C,

    // FLAG
    FLAG_GET : 0x10,
    FLAG_UPDATE_DB : 0x12,
    FLAG_CURTAIN_SWITCH : 0x16,
    FLAG_EDIT : 0x20,
    FLAG_EDIT_VALUE: 0x21,
    FLAG_EDIT_MORE_DEVICES : 0x23,
    FLAG_REQUEST_RS485_SCAN : 0x24,
    FLAG_CREATE : 0x25,
    FLAG_DELETE : 0x30,
    FLAG_DELETE_WIRELESS : 0x31,
    FLAG_RUN : 0x40,
    FLAG_SPECIAL : 0x43,
    FLAG_LISTING_MODULES: 0x50,
    FLAG_RGB: 0x51,
    FLAG_THERMOS_EDIT : 0x54,
    FLAG_THERMOS_GET : 0x55,
    FLAG_CONTROLLER_REGISTER: 0x56,
    FLAG_THERMOS_TABLET_ONOFF: 0x57,
    FLAG_RGB_GET: 0x59,
    FLAG_RGB_SWITCH_SET: 0x60,
    FLAG_RGB_SWITCH_GET: 0x61,
    FLAG_TRAVEL_STATE_SET: 0x63,
    FLAG_TRAVEL_STATE_GET: 0x64,
    FLAG_CURTAIN: 0x67,
    FLAG_ERROR :  0x80,

    // OTHER
    OPT_OUTPUT_SET_STATE : 0x01,
    OPT_OUTPUT_SET_TEMP_TIMER : 0x02,
    OPT_OUTPUT_GET_EDIT : 0x01,

    RES_OK :  0x01,

    CURTAIN_OPEN :  0x01,
    CURTAIN_CLOSE :  0x02,
    CURTAIN_STOP :  0x03,

}

export default Commands;